
services:
  polebot:
    pull_policy: build
    environment:
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - LOG_LEVELS=${LOG_LEVELS:-INFO}
      - LOG_LOCATION=/var/log/polebot
      - APP_CONFIG_DIR=/app/.config
      - APP_DISCORD_TOKEN=${APP_DISCORD_TOKEN}
    volumes:
    - polebot_logs:/var/log/polebot
    - /apps/polebot/.config:/app/.config

volumes:
  polebot_logs:
    external: true
    name: polebot_logs

networks:
  frontend-net:
    external: true
    name: nginx_hll_rcon_tool_1_server1
  backend-net:
    external: true
    name: mongodb_net
