
services:
  polebot:
    pull_policy: build
    environment:
      - LOG_LEVELS=${LOG_LEVELS:-:INFO}
      - LOG_LOCATION=/var/log/polebot
      - APP_MONGODB_CONNECTION_STRING=${APP_MONGODB_CONNECTION_STRING}
      - APP_MONGODB_DB_NAME=${APP_MONGODB_DB_NAME}
      - APP_DISCORD_TOKEN=${APP_DISCORD_TOKEN}
      - APP_DISCORD_OWNER_ID=${APP_DISCORD_OWNER_ID}
    volumes:
    - polebot_logs:/var/log/polebot
    - /apps/polebot/.config:/app/.config

volumes:
  polebot_logs:
    external: true
    name: polebot_logs

networks:
  crcon-net:
    external: true
    name: nginx_hll_rcon_tool_1_server1
  backend-net:
    external: true
    name: mongodb_net
