# Run this job on pushes to `main`, and for pull requests. If you don't specify
# `branches: [main], then this actions runs _twice_ on pull requests, which is
# annoying.
# Taken from https://jacobian.org/til/github-actions-poetry/


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12
  POETRY_VERSION: 1.8.2

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'

      - run: poetry install --no-interaction

      # Add the venv to the path. This is necessary because the pyright-action doesn't do it for you.
      - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
        name: Add poetry bin to path

      - uses: jakebailey/pyright-action@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - run: poetry run ruff check

      # Run tests. I'm using pytest and all my pytest config is in my `pyproject.toml`
      - run: poetry run pytest
